spring:
  application:
    name: "sale-customers"
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    maximum-pool-size: 10
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/changelog-master.xml
  quartz:
    jobs:
      scheduled-sync:
        enabled: true
        interval: 1h
logging:
  level:
    root: INFO

endpoint-sale-customer-wsdl: /SaleCustomerWS
